### ISSUE TITLE
Dropbox URL

### ISSUE THREAD

**Issue by platypus2021** [kgellatl/SignallingSingleCell#40]
HI,

I would like to reanalyze [this paper's result](https://www.science.org/doi/10.1126/scitranslmed.abd8995), and found that data and codes are available on github page [SignallingSingleCell](https://github.com/garber-lab/SignallingSingleCell).

I saw the phs002455_vignette.Rmd in the repository and I noticed that I could get the processed count data via the Dropbox URL, so I decided to use it to reanalyze.

However, I cannot download the data by the following command and It seems that the URL link is wrong/dead.
`load(url("https://www.dropbox.com/s/ipr7dys1ixd7f7m/phs002455_processed_UMItable.Rdata?dl=1"))`

There was no issue tab in garber-lab/SignallingSingleCell page since it was a forked page. I found this page is the original, thus I am asking the question here. Could you please fix the URL for phs002455_processed_UMItable.Rdata?

Best,

**Comment by kgellatl** [comment]
These links have been fixed, thanks for bringing it to my attention.

**Comment by platypus2021** [comment]
Hi kgellatl,

I could download the processed UMItable data. 
Thanks a lot.
